# Generated by Django 4.2.2 on 2023-06-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_rename_tarea_tarea_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=126)),
            ],
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
